DOMAIN = "weather_plus"

CONF_WEATHER_ENTITY = "weather_entity"
CONF_SUN_ENTITY = "sun_entity"
CONF_DAYTIME_MODE = "daytime_mode"
CONF_DAYTIME_START = "daytime_start"
CONF_DAYTIME_END = "daytime_end"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_DUAL_UNIT = "dual_unit"
CONF_ENABLE_CONDITIONS = "enable_conditions"
CONF_COLD_THRESHOLD = "cold_threshold"
CONF_HOT_THRESHOLD = "hot_threshold"

MODE_FIXED = "fixed"
MODE_SUN = "sun"
DAYTIME_MODES = (MODE_FIXED, MODE_SUN)

DEFAULT_SUN_ENTITY = "sun.sun"
DEFAULT_DAYTIME_MODE = MODE_FIXED
DEFAULT_DAYTIME_START = 6
DEFAULT_DAYTIME_END = 20
DEFAULT_UPDATE_INTERVAL = 30
DEFAULT_DUAL_UNIT = False
DEFAULT_ENABLE_CONDITIONS = False
DEFAULT_COLD_THRESHOLD = 65
DEFAULT_HOT_THRESHOLD = 80
