DOMAIN = "weather_plus"

CONF_WEATHER_ENTITY = "weather_entity"
CONF_SUN_ENTITY = "sun_entity"
CONF_DAYTIME_MODE = "daytime_mode"
CONF_MORNINGTIME_HOUR = "morningtime_hour"
CONF_DAYTIME_HOUR = "daytime_hour"
CONF_NIGHTTIME_HOUR = "nighttime_hour"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_DUAL_UNIT = "dual_unit"
CONF_ENABLE_CONDITIONS = "enable_conditions"
CONF_COLD_THRESHOLD = "cold_threshold"
CONF_HOT_THRESHOLD = "hot_threshold"
CONF_MOWER_PRECIP_ENTITY = "mower_precip_entity"
CONF_MOWER_TEMPERATURE_ENTITY = "mower_temperature_entity"

MODE_FIXED = "fixed"
MODE_SUN = "sun"
DAYTIME_MODES = (MODE_FIXED, MODE_SUN)

DEFAULT_SUN_ENTITY = "sun.sun"
DEFAULT_DAYTIME_MODE = MODE_FIXED
DEFAULT_MORNINGTIME_HOUR = 6
DEFAULT_DAYTIME_HOUR = 12
DEFAULT_NIGHTTIME_HOUR = 20
DEFAULT_UPDATE_INTERVAL = 30
DEFAULT_DUAL_UNIT = False
DEFAULT_ENABLE_CONDITIONS = False
DEFAULT_COLD_THRESHOLD = 65
DEFAULT_HOT_THRESHOLD = 80
